#ifndef VERSION_H
#define VERSION_H

#ifndef SIM_BUILD_COMMIT_OVERRIDE
#define SIM_BUILD_COMMIT_OVERRIDE "unknown"
#endif

#define SIM_SCHEMA_VERSION "1.0.0"
#define SIM_SOFTWARE_VERSION "0.3.0"
#define SIM_BUILD_COMMIT SIM_BUILD_COMMIT_OVERRIDE

#endif
